USE [master]
GO

/****** Object:  Database [MoviesDB]    Script Date: 12/11/2018 3:40:25 PM ******/
CREATE DATABASE [MoviesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MoviesDB', FILENAME = N'C:\SQLData\Data\MoviesDB.mdf' , SIZE = 512000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MoviesDB_log', FILENAME = N'C:\SQLData\Logs\MoviesDB_log.ldf' , SIZE = 102400KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MoviesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MoviesDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MoviesDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MoviesDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MoviesDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MoviesDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [MoviesDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MoviesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MoviesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MoviesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MoviesDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MoviesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MoviesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MoviesDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MoviesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MoviesDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MoviesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MoviesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MoviesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MoviesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MoviesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MoviesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MoviesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MoviesDB] SET RECOVERY FULL 
GO

ALTER DATABASE [MoviesDB] SET  MULTI_USER 
GO

ALTER DATABASE [MoviesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MoviesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MoviesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MoviesDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MoviesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MoviesDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MoviesDB] SET  READ_WRITE 
GO

